version: "3.4"

services:
     nodejsswarm:
          image: nodejsswarm
          build:
               context: .
               dockerfile: ./Dockerfile
          networks:
               - default
               - traefik-public\
          command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
          ports:
               - 4000:4000
               - 9229:9229
          env_file:
               - ./.env
