version: "3.6"

networks:
     traefik-public:
          external: true

services:
     nodejsswarm:
          image: ${DOCKER_REGISTRY}sapa-${ENV}-nodejs
          build:
               context: .
               dockerfile: ./Dockerfile
          networks:
               - default
               - traefik-public
          command: ["node", "./bin/www"]
          env_file:
               - ./.env
          ports:
               - 4000:4000
          deploy:
               labels:
                    - traefik.enable=true
                    - traefik.constraint-label=${TRAEFIK_PUBLIC_TAG?Variable not set}
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=Host(`${DOMAIN?Variable not set}`)
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.entrypoints=http
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.middlewares=https-redirect
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.rule=Host(`${DOMAIN?Variable not set}`)
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.entrypoints=https
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls=true
                    - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls.certresolver=le
                    - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=5000
